# Generated by Django 5.0.2 on 2024-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reservation_date', models.DateTimeField()),
                ('reservation_slot', models.SmallIntegerField(default=10)),
                ('no_of_guests', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item_description', models.TextField(default='', max_length=1000)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
