# Generated by Django 5.0.2 on 2024-02-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservation_date', 'reservation_slot')},
        ),
    ]
